#!/bin/bash
# Set Variables
resourceGroup=streamsets1
DATE=`date +%Y%m%d`

# Connect to Azure Gov via CLI
az cloud set --name AzureUSGovernment
az login -u thomasganka@covidtaskforce.onmicrosoft.us -p Roka3657

# Create Resource Group
az group create --name $resourceGroup --location "USGov Virginia"

 # Deploy a virtual network
az network vnet create --resource-group $resourceGroup --name streamsetsVnet --subnet-name streamsetsSubnet

# Create a public IP address
az network public-ip create --resource-group $resourceGroup --name sdcPublicIP

# Create a public IP address
az network public-ip create --resource-group $resourceGroup --name transformerPublicIP

# Create a public IP address
az network public-ip create --resource-group $resourceGroup --name schPublicIP

# Create a network security group.
az network nsg create --resource-group $resourceGroup --name streamsetsNetworkSecurityGroup

# Create a virtual network card and associate with public IP address and NSG.
az network nic create \
  --resource-group $resourceGroup \
  --name streamsetsNic \
  --vnet-name streamsetsVnet \
  --subnet streamsetsSubnet \
  --network-security-group streamsetsNetworkSecurityGroup \
  --public-ip-address sdcPublicIP

# Create a virtual network card and associate with public IP address and NSG.
az network nic create \
  --resource-group $resourceGroup \
  --name transformerNic \
  --vnet-name streamsetsVnet \
  --subnet streamsetsSubnet \
  --network-security-group streamsetsNetworkSecurityGroup \
  --public-ip-address transformerPublicIP

# Create a virtual network card and associate with public IP address and NSG.
az network nic create \
  --resource-group $resourceGroup \
  --name schNic \
  --vnet-name streamsetsVnet \
  --subnet streamsetsSubnet \
  --network-security-group streamsetsNetworkSecurityGroup \
  --public-ip-address schPublicIP

# Create network rule to allow ssh access
az network nsg rule create \
    --resource-group $resourceGroup \
    --nsg-name streamsetsNetworkSecurityGroup \
    --name streamsetsNetworkSecurityGroupRuleSSH \
    --protocol tcp \
    --priority 1000 \
    --destination-port-range 22 \
    --access allow

# Examine the rule
az network nsg show --resource-group $resourceGroup --name streamsetsNetworkSecurityGroup

# Create an availability set
az vm availability-set create \
    --resource-group $resourceGroup \
    --name streamsetsAvailabilitySet

# List Azure VMs
az vm image list

# Create a virtual machine for SDC
az vm create \
    --resource-group $resourceGroup \
    --name sdc \
    --location "USGov Virginia" \
    --availability-set streamsetsAvailabilitySet \
    --nics streamsetsNic \
    --image centos \
    --size "Standard_D4s_v3"

# Create a virtual machine for Transformer
az vm create \
    --resource-group $resourceGroup \
    --name transformer \
    --location "USGov Virginia" \
    --availability-set streamsetsAvailabilitySet \
    --nics transformerNic \
    --image centos \
    --size "Standard_D4s_v3"

# Create a virtual machine for Control Hub
az vm create \
    --resource-group $resourceGroup \
    --name sch \
    --location "USGov Virginia" \
    --availability-set streamsetsAvailabilitySet \
    --nics schNic \
    --image centos \
    --size "Standard_D4s_v3"

# Export ResourceGroup as a template
az group export --name $resourceGroup > template.json

# Create a deployment from Streamsets template
az deployment group create \
    --resource-group $resourceGroup \
    --template-file template.json


# Attach a managed persistent disk to a VM. (autogenerated)
#az vm disk attach --name sdcDisk-128 --resource-group $resourceGroup --vm-name sdc-$DATE --sku "Standard_LRS" --size-gb 128 --new
#az vm disk attach --name transformerDisk-128 --resource-group $resourceGroup --vm-name transformer-$DATE --sku "Standard_LRS" --size-gb 128 --new
#az vm disk attach --name schDisk-128 --resource-group $resourceGroup --vm-name sch-$DATE --sku "Standard_LRS" --size-gb 128 --new


# Open port 3389 to allow RDP traffic to host.
#az vm open-port --port 18630 --resource-group $resourceGroup --name sdc-$DATE